name: Update Framed Stats

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps
        run: npm ci

      - name: Generate framed-stats.svg
        run: node scripts/generate-framed.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/framed-stats.svg
          git commit -m "chore: update framed-stats.svg" --allow-empty
          git push
